# -*- coding: utf-8 -*-
"""RentRight-WebApp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jO9a220mkfndxr_ZHoqvVcLd2j_LeQSZ
"""

# 1. Library imports
!pip install uvicorn
import uvicorn
import pickle
import joblib
import numpy as np
!pip install FastAPI
from fastapi import FastAPI
from pydantic import BaseModel

class DataType(BaseModel):
    type  :  str
    area  :  str
    bed  :  int
    bath  : int
    toilet  :  int

from google.colab import files

uploaded = files.upload()

pip install catboost

#Create API and load model
app = FastAPI()
model = joblib.load("myModel.sav")

# Prediction
@app.get('/')
def index():
    return {"API" : "Ready to call"}

@app.post("/predict/")
def prediction(data: DataType):
    data = data.dict()
    type = data['type']
    area = data['area']
    bed = data['bed']
    bath = data['bath']
    toilet = data['toilet']
    result = model.predict([type, area, bed, bath, toilet])
    result = np.exp(result)
    
    return {'Expected rent is': result}


    if result:
        return {"statusCode": 200,
                "body": {"Expected rent": result}}
    else:
        return {"status": 404,
                "body": {"Message": "Are you sure you're using the right data ?"}}

# 4. Run the API with uvicorn
#    API will run on http://127.0.0.1:8000
if __name__ == '__main__':
    uvicorn.run(app, host='127.0.0.1', port=8000)